### ISSUE TITLE
`np.mul()` in `d_cal.py`

### ISSUE THREAD

**Issue by A-Buch** [mike-mendoza/py_banshee#1]
Thanks for the nice repo.
It seems that there is a small mix-up with the `np.mul()` function in `d_cal.py`: 
[errorneous_codeline](https://github.com/mike-mendoza/py_banshee/blob/ae35769f38334c7aa20ae8c8ff2a8b547597e3a9/py_banshee/d_cal.py#L261)

As far as i know  `np.mul()` doesn't exist in numpy, I assume that it is just a mix-up with `np.multiply()` and can be fixed quickly :)

**Comment by mike-mendoza** [comment]
Hi! Thank you for spotting the error.  The error has been fixed now :)
